// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvk6aelGjwVxa4GQ5W9vl70XI5xW5IVVg',
    appId: '1:544007931754:web:dd0b7aa8905f44101b0713',
    messagingSenderId: '544007931754',
    projectId: 'helloby',
    authDomain: 'helloby.firebaseapp.com',
    storageBucket: 'helloby.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByMTbuTtBkys80-ncSMTFuQTZNq7ncdXk',
    appId: '1:544007931754:android:3fd33906d3f2f1b01b0713',
    messagingSenderId: '544007931754',
    projectId: 'helloby',
    storageBucket: 'helloby.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbXGj_ZDay4EWUSIbasnZi930WURSCYa8',
    appId: '1:544007931754:ios:30af4f751a938db91b0713',
    messagingSenderId: '544007931754',
    projectId: 'helloby',
    storageBucket: 'helloby.appspot.com',
    iosClientId: '544007931754-upjjmuis92mgi89o2i41m2aa789126jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebaseproject',
  );
}
